---
ipam:
  mode: "kubernetes"

kubeProxyReplacement: disabled

enable-l2-announcements: true
kube-proxy-replacement: true

k8sServiceHost: localhost
k8sServicePort: 7445

k8s-client-qps: {QPS}
k8s-client-burst: {BURST}

cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

hubble:
  ui:
    enabled: true
  relay:
    enabled: true
