---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://kubernetes.github.io/ingress-nginx
  timeout: 3m
  
---  
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: system-nginx-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 30m

