---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: jameswynn-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: homepage-config-values