---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    name: homepage
resources:
  - helm-release.yaml
configMapGenerator:
  - name: homepage-config-values
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
