---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: "./charts/home-assistant"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    usb:
      enabled: true
      path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231031101717-if00"
    nodeSelector:
      feature.node.kubernetes.io/usb-02_1a86_55d4.present: 'true'
    ingress:
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Home Assistant"
        gethomepage.dev/description: "Home Assistant dashboard"
        gethomepage.dev/group: "Home"
        gethomepage.dev/icon: "homepage.png"