---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      priorityClassName: home-cluster-critical
      hostNetwork: true

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"  

        containers:
          main:
            image:
              repository: registry.skysolutions.fi/ghcr.io/onedr0p/home-assistant
              tag: 2024.7.4
            env:
              TZ: "Europe/Helsinki"
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 48m
                memory: 512M
              limits:
                memory: 800M
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1
            env:
              TZ: "Europe/Helsinki"
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
      code:
        type: ClusterIP
        controller: main
        ports:
          http:
            port: 8081

    ingress:
      main:
        enabled: true
        primary: true
        className: "nginx"
        hosts:
          - host: "home.intranet"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "home.intranet"


    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /config
      dockerenv:
        # Because of https://github.com/home-assistant/core/blob/0d66d298ec57b8e50379cc2ec31cbebf771705c3/homeassistant/util/package.py#L29
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /.dockerenv
