apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" .}}
  labels:
    {{- include "mealie.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mealie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "mealie.fullname" . }}
      labels:
        {{- include "mealie.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name | quote }}
          image: ghcr.io/mealie-recipes/mealie:v1.10.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: BASE_URL
              value: {{ .Values.service.url | quote }}
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Budapest"
            - name: MAX_WORKERS
              value: "1"
            - name: WEB_CONCURRENCY
              value: "1"
          volumeMounts:
            - name: mealie-data
              mountPath: "/app/data/"
          securityContext:
            privileged: true
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: {{ include "mealie.configPvc" . | quote }}