---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  labels:
    component.skylab.fi/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 8.3.7
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1

    grafana.ini:
      server:
        domain: monitoring.example.com
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - &host grafana.intranet
      tls:
        - hosts:
            - *host

    resources:
      limits:
        memory: 219M
      requests:
        cpu: 23m
        memory: 127M

    serviceMonitor:
      enabled: true
