---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  ingressClassName: NGINX
  tls:
    - hosts:
        - "{{ .Values.hostName }}"
  rules:
    - host: "{{ .Values.hostName }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: "http"