---
clusterName: aperture_cluster
endpoint: https://10.1.2.254:6443
allowSchedulingOnControlPlanes: true
additionalApiServerCertSans:
  - "127.0.0.1"
  - "10.1.2.254"
additionalMachineCertSans:
  - "127.0.0.1"
  - "10.1.2.254"

nodes:
  - hostname: APER-NODE-01
    controlPlane: true
    ipAddress: 10.1.2.1
    installDisk: /dev/nvme0n1
    machineDisks:
      - device: /dev/sda
        partitions:
          - mountpoint: /var/mnt/ext-store
    networkInterfaces: &networkInterfaces
      - interface: eth0
        vip:
          ip: 10.1.2.254
    machineFiles: &machineFiles
      - path: /etc/cri/conf.d/20-customization.part
        op: create
        permissions: 0
        content: |-
          [plugins."io.containerd.grpc.v1.cri"]
            enable_unprivileged_ports = true

  - hostname: APER-NODE-02
    controlPlane: true
    ipAddress: 10.1.2.2
    installDisk: /dev/nvme0n1
    machineDisks:
      - device: /dev/sda
        partitions:
          - mountpoint: /var/mnt/ext-store
    machineFiles: *machineFiles
    networkInterfaces: *networkInterfaces

patches:
  - "@patches/cni.yaml"
  - "@patches/dhcp.yaml"
#  - "@patches/kubelet-certificates.yaml"
#  - "@patches/longhorn-volume.yaml"
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools