---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi