apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-core
          image: "ghcr.io/onedr0p/home-assistant:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: HASS_HTTP_TRUSTED_PROXY_1
              value: "10.244.0.0/16"
            - name: TZ
              value: "Europe/Budapest"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: ha-config
              mountPath: /config
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            seccompProfile: { type: RuntimeDefault }
        - name: code-server
          image: "ghcr.io/coder/code-server:4.91.1"
          args: [
            "--auth", "none",
            "--user-data-dir", "/config/.vscode",
            "--extensions-dir", "/config/.vscode",
            "--port", "12321",
            "/config"
          ]
          ports:
              - name: http
                containerPort: 12321
                protocol: TCP
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: home-assistant-config