apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-core
          image: "ghcr.io/onedr0p/home-assistant:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: HASS_HTTP_TRUSTED_PROXY_1
              value: "10.244.0.0/16"
            - name: TZ
              value: "Europe/Budapest"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          volumeMounts:
            - name: ha-config
              mountPath: /config
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: home-assistant-config