apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 4 }}
      {{- end }}
      securityContext:
        fsGroup: 568
      containers:
        - name: {{ .Chart.Name }}-core
          image: "ghcr.io/onedr0p/home-assistant:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: HOME_ASSISTANT__HACS_INSTALL
              value: "true"
            - name: TZ
              value: "Europe/Budapest"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: ha-config
              mountPath: /config
            {{ if .Values.usb.enabled }}
            - name: usb
              mountPath: /dev/ttyACM0
            {{ end }}
          securityContext: &securityContext
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            seccompProfile: { type: RuntimeDefault }
        - name: code-server
          image: "ghcr.io/coder/code-server:4.91.1"
          args: [
            "--auth", "none",
            "--user-data-dir", "/config/.vscode",
            "--extensions-dir", "/config/.vscode",
            "--port", "12321",
            "/config"
          ]
          volumeMounts:
            - name: ha-config
              mountPath: /config
          ports:
              - name: http-code
                containerPort: 12321
                protocol: TCP
          securityContext: *securityContext
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: home-assistant-config
        {{ if .Values.usb.enabled }}
        - name: usb
          hostPath:
            path: "/dev/ttyUSB0"
        {{ end }}