---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: prom-stack-values
    namespace: monitoring
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true
