fullnameOverride: infra-prometheus
namespaceOverride: monitoring

prometheus:
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: "nginx"
    hosts:
      - "prometheus.intranet"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi


grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: Prometheus

defaultRules:
  create: false

alertmanager:
  enabled: false

kubernetesServiceMonitors:
  enabled: false

kubeProxy:
  enabled: false