fullnameOverride: infra-prometheus
namespaceOverride: monitoring

prometheus:
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: "nginx"
    hosts:
      - "prometheus.intranet"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

prometheus-node-exporter:
  fullnameOverride: node-exporter
  tolerations:
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node

grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: Prometheus

defaultRules:
  create: false

alertmanager:
  enabled: false

kubernetesServiceMonitors:
  enabled: true

kubeProxy:
  enabled: true