# Default values for home-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostName: "office.intranet"
codeServerHostName: "code.office.intranet"

nodeSelector: {}

usb:
  enabled: false
  path: "/dev/ttyUSB0"
  mountPath: "/dev/ttyUSB0"

ingress:
  enabled: true
  annotations: {}
  pathType: Prefix
  hosts:
    - "home-assistant.office.intranet"

codeServer:
  ingress:
    enabled: true
    annotations: {}
    pathType: Prefix
    hosts:
      - "code.office.intranet"